<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="41537" started-at="2022-02-01T11:05:07Z" finished-at="2022-02-01T11:05:49Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="41537" started-at="2022-02-01T11:05:07Z" finished-at="2022-02-01T11:05:49Z">
      <class name="test_scripts.LoginTestScript">
        <test-method status="PASS" signature="open()[pri:0, instance:test_scripts.LoginTestScript@ea4a92b]" name="open" is-config="true" duration-ms="25137" started-at="2022-02-01T16:35:07Z" finished-at="2022-02-01T16:35:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open -->
        <test-method status="FAIL" signature="test()[pri:0, instance:test_scripts.LoginTestScript@ea4a92b]" name="test" duration-ms="5761" started-at="2022-02-01T16:35:32Z" finished-at="2022-02-01T16:35:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at test_scripts.LoginTestScript.test(LoginTestScript.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="close(org.testng.ITestResult)[pri:0, instance:test_scripts.LoginTestScript@ea4a92b]" name="close" is-config="true" duration-ms="10624" started-at="2022-02-01T16:35:38Z" finished-at="2022-02-01T16:35:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test status=FAILURE method=LoginTestScript.test()[pri:0, instance:test_scripts.LoginTestScript@ea4a92b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- test_scripts.LoginTestScript -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
